apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-to-audio-service-deployment
  labels:
    app: video-to-audio-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: video-to-audio-svc
    spec:
      containers:
      - name: video-to-audio-svc
        image: video-to-audio